DECLARE 
  COD_FUNC NUMBER(3);
  V_SALARY EMPLOYEES.SALARY%TYPE;
BEGIN
  COD_FUNC := 107;
  SELECT SALARY INTO V_SALARY 
    FROM EMPLOYEES WHERE EMPLOYEE_ID = COD_FUNC;
  DBMS_OUTPUT.PUT_LINE('O SALARIO: ' || V_SALARY);
  
END;

/////////////////////////////////////////////////

CREATE OR REPLACE 
	FUNCTION FUNC_RETSALARIO(P_IDFUNC IN NUMBER)
		RETURN NUMBER
IS
  V_SALARY EMPLOYEES.SALARY%TYPE;
BEGIN

  SELECT SALARY INTO V_SALARY 
		FROM EMPLOYEES 
			WHERE EMPLOYEE_ID = P_IDFUNC;
			
  RETURN V_SALARY;
  
END;

///////////////////////////////////////////////////

 DECLARE
   X NUMBER;
 BEGIN
 
   X := FUNC_RETSALARIO(107);
   
   DBMS_OUTPUT.PUT_LINE('O SALARIO: ' || X);
   
 END;

///////////////////////////////////////////////////

CREATE OR REPLACE
	FUNCTION FUNC_RETSALARIO(P_IDFUNC IN NUMBER)
		RETURN NUMBER
IS
  V_SALARY EMPLOYEES.SALARY%TYPE;
  QTDE NUMBER(1);
BEGIN
  SELECT COUNT(*) INTO QTDE 
		FROM EMPLOYEES 
			WHERE EMPLOYEE_ID = P_IDFUNC;
  
  IF QTDE = 1 THEN
    SELECT SALARY INTO V_SALARY FROM EMPLOYEES WHERE EMPLOYEE_ID = P_IDFUNC;
  ELSE
    V_SALARY :=0;
  END IF;
  
	RETURN V_SALARY;
END;

/////////////////////////////////////////////////////

CREATE OR REPLACE
FUNCTION FUNC_RETDEPARAMENTO(P_IDDEPARTAMENTO IN NUMBER)
RETURN VARCHAR2
IS
  V_NOME DEPARTMENTS.DEPARTMENT_NAME%TYPE;
  QTDE NUMBER(1);
BEGIN
  SELECT COUNT(*) INTO QTDE 
  	FROM DEPARTMENTS 
  		WHERE DEPARTMENT_ID = P_IDDEPARTAMENTO;
 
  IF QTDE = 1 THEN
    SELECT DEPARTMENT_NAME INTO V_NOME 
    	FROM DEPARTMENTS WHERE DEPARTMENT_ID = P_IDDEPARTAMENTO;
  ELSE
    V_NOME := 'DEPARTAMENTO NÃO EXISTE';
  END IF;

    RETURN V_NOME;
  END;
  
  DECLARE
      X DEPARTMENTS.DEPARTMENT_NAME%TYPE;
  BEGIN

   X := FUNC_RETDEPARAMENTO(10);
   DBMS_OUTPUT.PUT_LINE('DEPARTAMENTO : ' || X);

  END;
   
   
     
  
 
  