----EXERCÍCIO----
CRIAR UMA FUNÇÃO QUE REALIZA O AUMENTO DOS FUNCIONÁRIO A PARTIR DE UM PERCENTUAL, DENTRO DE UM DEPARTAMENTO ESPECÍFICO. 
PARA ISSO SERÁ NECESSÁRIO RECEBER 2 PARÂMETROS, O PERCENTUAL E O ID DO DEPARTAMENTO. PARA ESSES DOIS CASOS DEVE TRATAR: 

- O PERCENTUAL DEVE ESTAR ENTRE 0 (ZERO) E 20, NÚMERO QUE REPRESENTA O PERCENTUAL DE AUMENTO (-999). 
- O ID DO DEPARTAMENTO DEVE SER VERIFICADO SE EXISTE OU NÃO FUNCIONÁRIOS, POIS SE NÃO EXISTIR NÃO DÁ PARA FAZER O AUMENTO (-998).

EXISTEM ALGUMAS REGRAS QUE DEVEM SER SEGUIDAS: 
 - NINGUÉM PODE GANAHAR MAIS QUE 20000 (CASO JÁ GUANHE MAIS DE 20000, DEVE FICAR COM O VALOR EXISTENTE, SE AO CLACULAR O NOVO VALOR ESTE FOR >=20000 
 DEVE SER FIXADO EM 20000).
- O FUNCIONÁRIO QUE ESTIVER COM JOB_ID AD_PRES NÃO PODE TER SEU DALÁRIO ALTERADO PELA FUNÇÃO.
A FUNÇÃO DEVE RETORNAR ZERO QUANDO FOR EXECUTADA COM SUCESSO, QUALQUER OUTRO NÚMERO INDICARÁ ERRO.
- TRATAR OS ERROS -EXCEPCION OTHER.


DROP TABLE FUNCIONARIO;


CREATE TABLE FUNCIONARIO AS SELECT * FROM HR.EMPLOYEES;

SELECT * FROM FUNCIONARIO;

SELECT * FROM FUNCIONARIO;

CREATE OR REPLACE 
FUNCTION AJUSTA_SALARIO(P_PERCENTUAL IN NUMBER, P_DEPARTAMENTO IN NUMBER)
RETURN NUMBER
IS
    RET NUMBER := 0;
    QTDE NUMBER;
    V_SALARIO_CALCULADO NUMBER := 0;
BEGIN
    IF P_PERCENTUAL > 0 AND P_PERCENTUAL <= 20 THEN
       
            SELECT COUNT(EMPLOYEE_ID) INTO QTDE FROM FUNCIONARIO
                    WHERE DEPARTMENT_ID = P_DEPARTAMENTO;
            IF QTDE > 0 THEN
            
              FOR RS IN (SELECT SALARY AS SALARIO, DEPARTMENT_ID, JOB_ID, EMPLOYEE_ID FROM FUNCIONARIO 
              WHERE DEPARTMENT_ID = P_DEPARTAMENTO AND SALARY < 20000 AND JOB_ID <> 'AD_PRES')
    LOOP
      
       
        IF RS.SALARIO < 20000 THEN
            V_SALARIO_CALCULADO := RS.SALARIO + ((P_PERCENTUAL/100) * RS.SALARIO  ); 
             DBMS_OUTPUT.PUT_LINE('descrição erro: ' || V_SALARIO_CALCULADO);
            IF V_SALARIO_CALCULADO > 20000 THEN
                UPDATE FUNCIONARIO SET SALARY = 20000 WHERE EMPLOYEE_ID = RS.EMPLOYEE_ID;
            ELSE
                UPDATE FUNCIONARIO SET SALARY = V_SALARIO_CALCULADO WHERE EMPLOYEE_ID = RS.EMPLOYEE_ID;
            END IF;
            
        END IF;
        
        V_SALARIO_CALCULADO := 0;
    END LOOP;

            ELSE
                RET := -998;
            END IF;
       
    ELSE
        RET := -999;
    END IF;
    COMMIT;
    RETURN RET;
EXCEPTION
   WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE('código erro: ' || SQLCODE);
      DBMS_OUTPUT.PUT_LINE('descrição erro: ' || SQLERRM);
      ROLLBACK;
      RETURN SQLCODE;
END;


DECLARE
    X NUMBER;
BEGIN
    X := AJUSTA_SALARIO(2, 50);
    DBMS_OUTPUT.PUT_LINE('X = ' || X);
END;


